export const skillLibrary = [
'AB Testing',
'ABAP',
'Account Management',
'Account Reconciliation',
'Account Strategy',
'Accounting',
'Accounts Administration',
'Accounts Management',
'Accounts Payable',
'Accounts Receivable',
'Active Directory',
'Actuarial Analysis',
'Acute Care',
'Adaptability',
'Administrative Support',
'Adobe Acrobat',
'Adobe After Effects',
'Adobe Analytics',
'Adobe Audition',
'Adobe Creative Suite',
'Adobe Experience Manager',
'Adobe Illustrator',
'Adobe InDesign',
'Adobe Lightroom',
'Adobe Photoshop',
'Adobe Premiere Pro',
'Adobe XD',
'Affiliate Marketing',
'Agile',
'Agile Coaching',
'Agile Delivery',
'Agricultural Engineering',
'Agriculture',
'AI Agents',
'AI Application Development',
'AI Automation',
'AI Ethics',
'AI Evaluation',
'AI Governance',
'AI Model Deployment',
'AI Product Management',
'AI Prompting',
'AI Safety',
'AI Strategy',
'AI Tools',
'Air Quality Monitoring',
'Air Traffic Control',
'Airbnb Management',
'Algorithm Design',
'Alteryx',
'Amazon Advertising',
'Amazon EC2',
'Amazon ECS',
'Amazon EKS',
'Amazon FBA',
'Amazon Redshift',
'Amazon S3',
'Amazon SageMaker',
'Amazon Web Services',
'Analytical Thinking',
'Anatomy',
'Android Development',
'Android Studio',
'Angular',
'Animation',
'Anomaly Detection',
'Ansible',
'Anthropology',
'Apache Airflow',
'Apache Beam',
'Apache Cassandra',
'Apache Flink',
'Apache Hive',
'Apache Kafka',
'Apache NiFi',
'Apache Spark',
'API Design',
'API Development',
'API Documentation',
'API Integration',
'API Security',
'Apollo GraphQL',
'App Store Optimization',
'Application Support',
'Applied Mathematics',
'AR Development',
'Arbitration',
'Archiving',
'Argo CD',
'Artificial Intelligence',
'ASP.NET',
'ASP.NET Core',
'Assembly Language',
'Asset Management',
'Assistive Technology',
'Asynchronous Programming',
'Athletic Training',
'Atlassian Confluence',
'Atlassian Jira',
'Attention to Detail',
'Audio Editing',
'Audio Engineering',
'Audit Management',
'Augmented Reality',
'Authentication',
'Authorization',
'AutoCAD',
'AutoCAD Civil 3D',
'Automated Testing',
'Automation',
'Autonomous Systems',
'AWS',
'AWS CloudFormation',
'AWS Glue',
'AWS Lambda',
'AWS RDS',
'AWS Security',
'Azure',
'Azure Active Directory',
'Azure AI Services',
'Azure App Service',
'Azure Blob Storage',
'Azure Data Factory',
'Azure DevOps',
'Azure Functions',
'Azure Kubernetes Service',
'Azure Machine Learning',
'Azure SQL Database',
'B2B Marketing',
'B2B SaaS',
'B2B Sales',
'B2C Marketing',
'B2C Sales',
'Backend Development',
'Backlog Management',
'Backup and Recovery',
'Bank Reconciliation',
'Bash',
'Behavioral Analysis',
'Behavioral Interviewing',
'Benchmarking',
'Benefits Administration',
'Big Data',
'BigQuery',
'Bilingual Communication',
'Billing',
'Biochemistry',
'Bioinformatics',
'Biology',
'Biomedical Engineering',
'Biostatistics',
'Biotechnology',
'Blender',
'Blockchain',
'Blog Writing',
'Book Publishing',
'Bookkeeping',
'Bootstrap',
'Brand Management',
'Brand Positioning',
'Brand Strategy',
'Budget Forecasting',
'Budget Management',
'Budgeting',
'Bug Tracking',
'Building Information Modeling',
'Business Analysis',
'Business Continuity Planning',
'Business Development',
'Business Intelligence',
'Business Operations',
'Business Process Improvement',
'Business Process Modeling',
'Business Strategy',
'Business Writing',
'C',
'C#',
'C++',
'CAD Design',
'CAE',
'Calibration',
'CAM',
'Campaign Management',
'Canva',
'Capacity Planning',
'Care Coordination',
'Career Coaching',
'Case Management',
'Cash Flow Management',
'Cash Handling',
'Cassandra',
'Category Management',
'Cell Culture',
'Change Control',
'Change Management',
'Character Design',
'Chatbot Development',
'Chef',
'Chemical Analysis',
'Chemical Engineering',
'Chemistry',
'Childcare',
'CI/CD',
'CI/CD Pipelines',
'Cinematography',
'CircleCI',
'Civil Engineering',
'Claims Management',
'Claims Processing',
'Client Relations',
'Clinical Data Management',
'Clinical Documentation',
'Clinical Operations',
'Clinical Pharmacy',
'Clinical Research',
'Clinical Trial Management',
'Cloud Architecture',
'Cloud Computing',
'Cloud Cost Optimization',
'Cloud Migration',
'Cloud Security',
'CloudFormation',
'CNC Programming',
'Coaching',
'Cognitive Psychology',
'Cold Calling',
'Cold Emailing',
'Collaboration',
'Commissioning',
'Communication',
'Community Outreach',
'Compensation and Benefits',
'Competitive Analysis',
'Compiler Design',
'Compliance',
'Computer Networking',
'Computer Vision',
'Concept Art',
'Configuration Management',
'Conflict Resolution',
'Confluence',
'Construction Estimation',
'Construction Management',
'Construction Safety',
'Consultative Selling',
'Consumer Insights',
'Containerization',
'Content Creation',
'Content Editing',
'Content Marketing',
'Content Strategy',
'Continuous Integration',
'Contract Management',
'Conversion Rate Optimization',
'Copy Editing',
'Copywriting',
'Core Java',
'Corporate Communications',
'Corporate Finance',
'Corporate Law',
'Corporate Strategy',
'Cost Accounting',
'Cost Control',
'Cost Estimation',
'Counseling',
'Creative Direction',
'Creative Writing',
'Crisis Management',
'Critical Thinking',
'CRM',
'Cross-Browser Testing',
'Cross-Functional Leadership',
'Cross-Platform Development',
'Cryptography',
'CSS',
'Customer Development',
'Customer Experience',
'Customer Onboarding',
'Customer Relationship Management',
'Customer Retention',
'Customer Service',
'Customer Success',
'Customer Success Management',
'Cybersecurity',
'Cypress',
'Dart',
'Data Analysis',
'Data Analytics',
'Data Annotation',
'Data Architecture',
'Data Cataloging',
'Data Cleaning',
'Data Collection',
'Data Engineering',
'Data Entry',
'Data Ethics',
'Data Governance',
'Data Integration',
'Data Lake',
'Data Management',
'Data Migration',
'Data Modeling',
'Data Pipeline Development',
'Data Privacy',
'Data Quality',
'Data Science',
'Data Security',
'Data Storytelling',
'Data Validation',
'Data Visualization',
'Data Warehousing',
'Database Administration',
'Database Design',
'Database Development',
'Database Migration',
'Databricks',
'Datadog',
'DB2',
'dbt',
'Decision Making',
'Deep Learning',
'Deep Reinforcement Learning',
'Demand Forecasting',
'Demand Generation',
'Dental Assistance',
'Design Systems',
'Detail Orientation',
'DevOps',
'DevSecOps',
'Diagnostic Imaging',
'Digital Advertising',
'Digital Marketing',
'Digital Strategy',
'Digital Transformation',
'Direct Sales',
'Disaster Recovery',
'Distribution Management',
'Diversity and Inclusion',
'Django',
'Django REST Framework',
'DNS Management',
'Docker',
'Docker Compose',
'Documentation',
'Documentation Writing',
'Domain Knowledge',
'Domain-Driven Design',
'Drafting',
'DynamoDB',
'E-commerce',
'E-discovery',
'E-learning',
'Editing',
'EHR Implementation',
'Elasticsearch',
'Electrical Engineering',
'Electronic Engineering',
'Electronic Health Records',
'Email Deliverability',
'Email Marketing',
'Embedded Systems',
'Emergency Management',
'Employee Engagement',
'Employee Relations',
'Employee Training',
'End-to-End Testing',
'Endpoint Security',
'Energy Management',
'Engineering Design',
'Engineering Management',
'Enterprise Architecture',
'Enterprise Resource Planning',
'Enterprise Sales',
'Entrepreneurship',
'Environmental Compliance',
'Environmental Engineering',
'Environmental Health and Safety',
'Equal Employment Opportunity',
'Equity Research',
'ERP',
'Escalation Management',
'ETL',
'Event Coordination',
'Event Management',
'Excel',
'Executive Communication',
'Executive Support',
'Experiment Design',
'Express.js',
'Facilities Management',
'FastAPI',
'FDA Compliance',
'Feature Engineering',
'Figma',
'Film Editing',
'Finance',
'Financial Accounting',
'Financial Analysis',
'Financial Modeling',
'Financial Planning',
'Financial Reporting',
'Finite Element Analysis',
'Fire Safety',
'Firebase',
'First Aid',
'Flask',
'Fleet Management',
'Flow Cytometry',
'Flutter',
'Food Safety',
'Forecasting',
'Forensic Accounting',
'Forensic Analysis',
'Fraud Detection',
'French',
'Frontend Development',
'Full-Stack Development',
'Functional Testing',
'Fundraising',
'GA4',
'Game Design',
'GCP BigQuery',
'GDPR',
'Generative AI',
'Geographic Information Systems',
'Geology',
'German',
'Git',
'GitHub',
'GitHub Actions',
'GitLab',
'GitLab CI/CD',
'Go',
'Goal Setting',
'Google Ad Manager',
'Google Ads',
'Google Analytics',
'Google Cloud',
'Google Cloud Platform',
'Google Data Studio',
'Google Looker Studio',
'Google Sheets',
'Google Tag Manager',
'Governance Risk and Compliance',
'Graph Databases',
'Graphic Design',
'GraphQL',
'Great Expectations',
'Green Building',
'Groovy',
'Growth Marketing',
'GSC',
'GST',
'Guest Relations',
'GUI Development',
'Hadoop',
'Hardware Troubleshooting',
'HBase',
'Health and Safety',
'Healthcare Administration',
'Healthcare Compliance',
'Healthcare Operations',
'Helm',
'Help Desk Support',
'High-Performance Computing',
'HIPAA',
'Hiring',
'Home Care',
'Hospitality Management',
'HTML',
'HubSpot',
'Human Resources',
'HVAC',
'Hydraulic Systems',
'IAM',
'IFRS',
'Illustration',
'Illustrator',
'Image Processing',
'Import Export',
'Inbound Marketing',
'Incident Management',
'Industrial Automation',
'Industrial Design',
'Industrial Engineering',
'Industrial Safety',
'Influencer Marketing',
'Influencer Outreach',
'Information Architecture',
'Information Security',
'Infrastructure as Code',
'Infrastructure Management',
'Innovation',
'Inspection',
'Instructional Design',
'Insurance',
'Insurance Claims',
'Interaction Design',
'Internal Audit',
'International Business',
'International Sales',
'Interviewing',
'Inventory Control',
'Inventory Forecasting',
'Inventory Management',
'iOS Development',
'iPadOS Development',
'ISO 27001',
'ISO 9001',
'Issue Resolution',
'IT Asset Management',
'IT Audit',
'IT Governance',
'IT Project Management',
'IT Service Management',
'Italian',
'ITIL',
'J2EE',
'Java',
'Java Spring',
'JavaFX',
'JavaScript',
'Jenkins',
'Jest',
'Jira',
'Job Coaching',
'Journalism',
'jQuery',
'JSON',
'Julia',
'Jupyter',
'Kaizen',
'Kanban',
'Key Account Management',
'Knowledge Management',
'Kotlin',
'Kotlin Multiplatform',
'KPI Tracking',
'Kubernetes',
'KYC',
'Labor Relations',
'Laboratory Techniques',
'Landscape Design',
'Laravel',
'Laravel Development',
'Lead Generation',
'Lead Nurturing',
'Leadership',
'Lean Manufacturing',
'Learning Management Systems',
'Legal Compliance',
'Legal Drafting',
'Legal Research',
'Lesson Planning',
'Licensing',
'Life Sciences',
'Linear Algebra',
'LinkedIn Ads',
'Linux',
'Linux Administration',
'Litigation Support',
'Live Streaming',
'LLM Application Development',
'LLM Evaluation',
'LLM Fine-Tuning',
'LLM Guardrails',
'LLM Observability',
'LLMOps',
'Load Testing',
'Localization',
'Logistics',
'Looker',
'Machine Learning',
'Machine Learning Engineering',
'MacOS Administration',
'Magento',
'Maintenance Management',
'Management',
'Manual Testing',
'Manufacturing',
'Manufacturing Engineering',
'Market Analysis',
'Market Research',
'Marketing Analytics',
'Marketing Automation',
'Marketing Strategy',
'Material Planning',
'Mathematics',
'MATLAB',
'Mechanical Engineering',
'Media Buying',
'Media Planning',
'Medical Billing',
'Medical Coding',
'Medical Devices',
'Medical Records',
'Medical Terminology',
'Medical Writing',
'Mentoring',
'Merchandising',
'Microbiology',
'Microservices',
'Microsoft Access',
'Microsoft Azure',
'Microsoft Dynamics',
'Microsoft Dynamics 365',
'Microsoft Excel',
'Microsoft Office',
'Microsoft Power Apps',
'Microsoft Power Automate',
'Microsoft Power BI',
'Microsoft PowerPoint',
'Microsoft Project',
'Microsoft SQL Server',
'Microsoft Teams',
'Microsoft Word',
'Middleware',
'Mobile App Testing',
'Mobile Development',
'Model Evaluation',
'Model Monitoring',
'Model Risk Management',
'Model Serving',
'Molecular Biology',
'MongoDB',
'Motion Design',
'Motion Graphics',
'MS SQL Server',
'Multi-Agent Systems',
'Multitasking',
'Music Production',
'MySQL',
'Natural Language Processing',
'Negotiation',
'Negotiation Strategy',
'NestJS',
'Network Administration',
'Network Engineering',
'Network Monitoring',
'Network Security',
'Networking',
'Neural Networks',
'Next.js',
'Next.js Development',
'Nginx',
'No-Code Development',
'Node.js',
'Node.js Development',
'Nonprofit Management',
'NoSQL',
'NoSQL Databases',
'NPM',
'Nuclear Engineering',
'NumPy',
'Nursing',
'Nutrition',
'OAuth',
'Object Detection',
'Object-Oriented Programming',
'Objective-C',
'Occupational Health and Safety',
'OKR Management',
'Onboarding',
'Online Advertising',
'OpenAPI',
'OpenCV',
'OpenShift',
'OpenTelemetry',
'Operations Management',
'Operations Research',
'Oracle',
'Oracle Cloud',
'Oracle Database',
'Order Management',
'Organizational Change',
'Organizational Development',
'Organizational Skills',
'Outbound Sales',
'Outreach',
'Pandas',
'Patent Research',
'Payment Processing',
'Payroll',
'Penetration Testing',
'People Management',
'Performance Marketing',
'Performance Optimization',
'Performance Reviews',
'Performance Testing',
'Perl',
'Personal Training',
'Pharmaceutical Sales',
'Pharmacology',
'Pharmacovigilance',
'Photo Retouching',
'Photography',
'PHP',
'PHP Development',
'Physics',
'Pipeline Management',
'PL/SQL',
'Planning',
'Playwright',
'PLC Programming',
'Policy Analysis',
'PostgreSQL',
'PostgreSQL Administration',
'Power BI',
'PowerPoint',
'PowerShell',
'PPC Advertising',
'PRD Writing',
'Predictive Analytics',
'Predictive Modeling',
'Presales',
'Presentation Skills',
'Pricing Analysis',
'Pricing Strategy',
'Print Production',
'Privacy Compliance',
'Problem Solving',
'Process Automation',
'Process Engineering',
'Process Improvement',
'Process Mapping',
'Procurement',
'Product Analytics',
'Product Design',
'Product Development',
'Product Management',
'Product Marketing',
'Product Operations',
'Product Roadmapping',
'Production Planning',
'Production Support',
'Program Evaluation',
'Program Management',
'Project Coordination',
'Project Management',
'Project Planning',
'Prompt Engineering',
'Proofreading',
'Prospecting',
'Prototyping',
'Psychology',
'Public Policy',
'Public Relations',
'Public Speaking',
'Publishing',
'Puppet',
'Purchasing',
'PySpark',
'Python',
'PyTorch',
'QA Automation',
'Qualitative Research',
'Quality Assurance',
'Quality Control',
'Quality Engineering',
'Quantitative Analysis',
'QuickBooks',
'R',
'RabbitMQ',
'Radiology',
'React',
'React Native',
'Real Estate Management',
'Real Estate Sales',
'Recommendation Systems',
'Records Management',
'Recruiting',
'Recruitment Marketing',
'Redis',
'Regression Testing',
'Regulatory Affairs',
'Regulatory Compliance',
'Reinforcement Learning',
'Relationship Building',
'Release Engineering',
'Release Management',
'Reliability Engineering',
'Remote Collaboration',
'Reporting',
'Requirements Analysis',
'Requirements Gathering',
'Research',
'Research Design',
'Resilience',
'Resource Allocation',
'Responsive Design',
'REST API Development',
'Retail Management',
'Retail Operations',
'Revenue Growth',
'Revenue Operations',
'Risk Analysis',
'Risk Assessment',
'Risk Management',
'Robotic Process Automation',
'Robotics',
'Root Cause Analysis',
'Routing and Switching',
'Ruby',
'Ruby on Rails',
'Rust',
'SaaS',
'Sales',
'Sales Enablement',
'Sales Forecasting',
'Sales Operations',
'Sales Strategy',
'Salesforce',
'Salesforce Administration',
'Salesforce Development',
'SAML',
'SAP',
'SAP ABAP',
'SAP ERP',
'SAP FICO',
'SAP HANA',
'SAP SuccessFactors',
'SAS',
'Scala',
'Scheduling',
'Scrum',
'Search Engine Marketing',
'Search Engine Optimization',
'Secure Coding',
'Security Architecture',
'Security Compliance',
'Security Engineering',
'Security Incident Response',
'Security Operations',
'Security Testing',
'Selenium',
'SEM',
'SEO',
'SEO Auditing',
'SEO Content Writing',
'Server Administration',
'Serverless Architecture',
'Service Delivery',
'ServiceNow',
'SharePoint',
'Shell Scripting',
'Shopify',
'Shopify Development',
'SIEM',
'Six Sigma',
'SLA Management',
'Slack',
'Snowflake',
'Social Media Advertising',
'Social Media Management',
'Social Media Marketing',
'Software Architecture',
'Software Design',
'Software Development',
'Software Engineering',
'Software Implementation',
'Software Quality Assurance',
'Software Testing',
'Solidity',
'Solution Architecture',
'Solution Selling',
'Sourcing',
'Spanish',
'Spark',
'Spark SQL',
'Speech Recognition',
'Speech Writing',
'Spring Boot',
'SQL',
'SQLite',
'SRE',
'SSO',
'Staff Training',
'Stakeholder Management',
'Stata',
'Statistical Analysis',
'Statistical Modeling',
'Stock Management',
'Storytelling',
'Strategic Communications',
'Strategic Planning',
'Strategic Sourcing',
'Streamlit',
'Structural Engineering',
'Supplier Management',
'Supply Chain Management',
'Supply Planning',
'Support Engineering',
'Surgery Assistance',
'Survey Design',
'Sustainability',
'Svelte',
'Swift',
'SwiftUI',
'System Administration',
'Systems Design',
'Tableau',
'Tableau Development',
'Talent Acquisition',
'Talent Management',
'Tax Accounting',
'Tax Compliance',
'Tax Preparation',
'Teaching',
'Team Building',
'Team Leadership',
'Technical Documentation',
'Technical Recruiting',
'Technical SEO',
'Technical Support',
'Technical Training',
'Technical Troubleshooting',
'Technical Writing',
'Telecommunications',
'Telemedicine',
'TensorFlow',
'TensorFlow Serving',
'Terraform',
'Test Automation',
'Test Case Design',
'Test Planning',
'Testing',
'Threat Intelligence',
'Threat Modeling',
'Time Management',
'Time Series Analysis',
'Tosca',
'Training and Development',
'Training Delivery',
'Transformer Models',
'Translation',
'Travel Planning',
'Treasury Management',
'Troubleshooting',
'Troubleshooting Skills',
'TypeScript',
'TypeScript Development',
'UAT',
'Ubuntu',
'UI Design',
'UI/UX',
'Underwriting',
'Unity',
'Unix',
'Unreal Engine',
'Usability Testing',
'User Acceptance Testing',
'User Experience Research',
'User Interface Design',
'User Research',
'UX Design',
'UX Research',
'UX Writing',
'Vendor Management',
'Vendor Negotiation',
'Version Control',
'Veterinary Assistance',
'Video Editing',
'Video Production',
'Virtual Assistance',
'Virtual Reality',
'Visual Basic',
'Visual Design',
'VMware',
'Voice User Interface Design',
'Vue.js',
'Vue.js Development',
'Vulnerability Assessment',
'Warehouse Management',
'Warehouse Operations',
'Waterfall Project Management',
'Web Accessibility',
'Web Analytics',
'Web Application Security',
'Web Design',
'Web Development',
'Web Performance Optimization',
'Web Scraping',
'Web Security',
'Webpack',
'Welding',
'Windows Administration',
'Windows Server',
'Wireframing',
'WooCommerce',
'WordPress',
'WordPress Development',
'Workflow Optimization',
'Workforce Management',
'Workforce Planning',
'Workshop Facilitation',
'Writing',
'Writing and Editing',
'Xamarin',
'Xero',
'XML',
'YAML',
'Yield Management',
'Zendesk',
'Zero Trust Security',
];

const normalizeSkill = (value) => value.trim().toLowerCase();

export const getSkillSuggestions = (query, selectedSkills = [], limit = 12) => {
  const normalizedQuery = normalizeSkill(query);
  const selectedSet = new Set(selectedSkills.map(normalizeSkill));

  const availableSkills = skillLibrary.filter((skill) => !selectedSet.has(normalizeSkill(skill)));
  if (!normalizedQuery) {
    return availableSkills.slice(0, limit);
  }

  return availableSkills
    .filter((skill) => normalizeSkill(skill).startsWith(normalizedQuery))
    .slice(0, limit);
};
