export const professionalTemplateConfigs = {
  'ats-friendly': { name: 'ATS Friendly', role: 'ATS Ready', accent: '#0f172a', layout: 'plain' },
  'business-analyst': { name: 'Business Analyst', role: 'Analytics', accent: '#2563eb', layout: 'analyst' },
  'career-pivot': { name: 'Career Pivot', role: 'Career Change', accent: '#7c3aed', layout: 'pivot' },
  'fresh-graduate-internship': { name: 'Fresh Graduate', role: 'Entry Level', accent: '#2563eb', layout: 'graduate' },
  'internal-promotion-transfer': { name: 'Internal Promotion', role: 'Internal Move', accent: '#475569', layout: 'internal' },
  'solution-architect': { name: 'Solution Architect', role: 'Architecture', accent: '#334155', layout: 'blueprint' },
  'professional-plain': { name: 'Professional Plain', role: 'Plain', accent: '#0f172a', layout: 'plain-alt' },
  'media-person': { name: 'Media Person', role: 'Editorial', accent: '#dc2626', layout: 'editorial' },
  'professional-editorial': { name: 'Professional Editorial', role: 'Editorial', accent: '#b91c1c', layout: 'editorial-alt' },
  'medical-professional': { name: 'Medical Professional', role: 'Healthcare', accent: '#0d9488', layout: 'clinical' },
  'professional-clinical': { name: 'Professional Clinical', role: 'Healthcare', accent: '#0f766e', layout: 'clinical-alt' },
  'nurse-clinical': { name: 'Nurse Clinical', role: 'Healthcare', accent: '#059669', layout: 'clinical-soft' },
  'legal-counsel': { name: 'Legal Counsel', role: 'Formal', accent: '#1e3a8a', layout: 'formal' },
  'professional-formal': { name: 'Professional Formal', role: 'Formal', accent: '#1e3a8a', layout: 'formal-alt' },
  'finance-analyst': { name: 'Finance Analyst', role: 'Finance', accent: '#047857', layout: 'ledger' },
  'data-scientist': { name: 'Data Scientist', role: 'Data', accent: '#7c3aed', layout: 'data' },
  'product-manager': { name: 'Product Manager', role: 'Product', accent: '#0891b2', layout: 'product' },
  referral: { name: 'Referral', role: 'Networking', accent: '#0f766e', layout: 'referral' },
  'relocation-remote': { name: 'Relocation / Remote', role: 'Remote', accent: '#0891b2', layout: 'remote' },
  'teacher-educator': { name: 'Teacher Educator', role: 'Academic', accent: '#ca8a04', layout: 'academic-soft' },
  hospitality: { name: 'Hospitality', role: 'Service', accent: '#c2410c', layout: 'service' },
  'sales-executive': { name: 'Sales Executive', role: 'Revenue', accent: '#be123c', layout: 'sales' },
  'marketing-manager': { name: 'Marketing Manager', role: 'Marketing', accent: '#db2777', layout: 'campaign' },
  'software-engineer': { name: 'Software Engineer', role: 'Technical', accent: '#0369a1', layout: 'technical' },
  'professional-technical': { name: 'Professional Technical', role: 'Technical', accent: '#0f172a', layout: 'technical-alt' },
  'project-manager': { name: 'Project Manager', role: 'Delivery', accent: '#4f46e5', layout: 'milestone' },
  'ux-designer': { name: 'UX Designer', role: 'Creative', accent: '#9333ea', layout: 'portfolio' },
  'operations-manager': { name: 'Operations Manager', role: 'Operations', accent: '#475569', layout: 'ops' },
  'hr-recruiter': { name: 'HR Recruiter', role: 'People', accent: '#0f766e', layout: 'people' },
  government: { name: 'Government', role: 'Civic', accent: '#1f2937', layout: 'civic' },
  'ceo-portrait': { name: 'Boardroom Portrait', role: 'Executive', accent: '#2F4156', layout: 'executive-portrait' },
  'ceo-board-letter': { name: 'CEO Board Letter', role: 'Executive', accent: '#111827', layout: 'executive-board-letter' },
  'executive-letter': { name: 'Executive Letter', role: 'Executive', accent: '#1f3a8a', layout: 'executive-letter' },
  'managing-director-photo': { name: 'Editorial Photo', role: 'Executive', accent: '#111827', layout: 'executive-minimal-photo' },
  'ceo-blue-header': { name: 'Blue Header', role: 'Executive', accent: '#2f7fbd', layout: 'executive-blue-header' },
  'executive-banner-letter': { name: 'Banner Letter', role: 'Executive', accent: '#c8a15d', layout: 'executive-banner-letter' },
  'ceo-strategy-bar': { name: 'Strategy Bar', role: 'Executive', accent: '#0072bc', layout: 'executive-strategy-bar' },
  'cfo-boardroom': { name: 'Boardroom Ledger', role: 'Boardroom', accent: '#047857', layout: 'executive-board' },
  'cto-innovation': { name: 'Innovation Header', role: 'Technology', accent: '#0369a1', layout: 'executive-tech' },
  'executive-gold-frame': { name: 'Gold Frame', role: 'Executive', accent: '#c89a57', layout: 'executive-gold-frame' },
  'executive-leadership-classic': { name: 'Leadership Classic', role: 'Executive', accent: '#c9a15d', layout: 'executive-leadership-classic' },
  'vp-operations-executive': { name: 'Operations Slate', role: 'Operations', accent: '#567C8D', layout: 'executive-ops' },
  'executive-profile-sidebar': { name: 'Profile Sidebar', role: 'Executive', accent: '#bf9250', layout: 'executive-profile-sidebar' },
  'director-slate': { name: 'Slate Leadership', role: 'Executive', accent: '#334155', layout: 'executive-slate' },
  'president-classic': { name: 'Classic Enterprise', role: 'Classic', accent: '#1e3a8a', layout: 'executive-classic' },
  'chief-people-officer': { name: 'People Boardroom', role: 'People', accent: '#be123c', layout: 'executive-people' },
  'gamer-arena': { name: 'Gamer Arena', role: 'Graphic', accent: '#facc15', layout: 'artistic-gamer' },
  'magazine-cover': { name: 'Magazine Cover', role: 'Graphic', accent: '#dc2626', layout: 'artistic-magazine' },
  'sql-terminal': { name: 'SQL Terminal', role: 'Graphic', accent: '#fb923c', layout: 'artistic-terminal' },
  'youtube-creator': { name: 'YouTube Creator', role: 'Graphic', accent: '#ef4444', layout: 'artistic-video' },
  'architect-grid': { name: 'Architect', role: 'Graphic', accent: '#2563eb', layout: 'artistic-architect' },
  'student-notes': { name: 'Student Notes', role: 'Graphic', accent: '#2563eb', layout: 'artistic-student-notes' },
  'motion-designer-board': { name: 'Motion Designer Board', role: 'Graphic', accent: '#facc15', layout: 'artistic-motion-board' },
  'super-exclusive': { name: 'Super Exclusive', role: 'Executive', accent: '#c4954f', layout: 'executive-super-exclusive' },
  'ultra-exclusive': { name: 'Ultra Exclusive', role: 'Executive', accent: '#c6a15b', layout: 'executive-ultra-exclusive' },
};
